language: java
addons:
  sonarcloud:
    organization: "superdevsteph"
    token:
      secure: "f62b200f1d7883b5a10bbd6140c047f8cbeed533" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=superdevsteph_P9_src
  - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar